### ISSUE TITLE
SEVERE: Failed to instantiate class of type: com.zandero.rest.example.rest.EchoRest, class needs empty constructor!

### ISSUE THREAD

**Issue by tnguyen-lh** [zandero/rest.vertx#27]
I downloaded rest.vertx.example and run it, exception throw when I access /echo
If I create a new empty constructor, guice could not inject MyService into the rest

SEVERE: Failed to instantiate class of type: com.zandero.rest.example.rest.EchoRest, class needs empty constructor!
java.lang.IllegalArgumentException: Failed to instantiate class of type: com.zandero.rest.example.rest.EchoRest, class needs empty constructor!
	at com.zandero.rest.RestRouter.register(RestRouter.java:118)
	at com.zandero.rest.RestRouter.register(RestRouter.java:80)
	at com.zandero.rest.RestBuilder.getRouter(RestBuilder.java:328)
	at com.zandero.rest.RestBuilder.build(RestBuilder.java:360)
	at com.zandero.rest.example.ServerVerticle.start(ServerVerticle.java:58)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)

**Comment by drejc** [comment]
Example code was not pushed ... update to latest version.
PS: Please post issues like this to the example project next time.
