### ISSUE TITLE
DELETE endpoints cannot have a body

### ISSUE THREAD

**Issue by gofabian** [zandero/rest.vertx#42]
The HTTP method "DELETE" is allowed to have a body. But rest.vertx does not allow.

```
Exception in thread "vert.x-eventloop-thread-0" java.lang.IllegalArgumentException: one.two.three.MyController.delete(Payload arg0) - Missing argument annotation (@PathParam, @QueryParam, @FormParam, @HeaderParam, @CookieParam or @Context) for: arg0!
	at com.zandero.utils.Assert.isFalse(Assert.java:38)
	at com.zandero.utils.Assert.isTrue(Assert.java:51)
	at com.zandero.rest.AnnotationProcessor.get(AnnotationProcessor.java:65)
	at com.zandero.rest.RestRouter.register(RestRouter.java:124)
	at com.zandero.rest.RestBuilder.getRouter(RestBuilder.java:406)
	at com.zandero.rest.RestBuilder.build(RestBuilder.java:451)
```

**Comment by gofabian** [comment]
Wow! That was fast :) Do you plan a bugfix release?

**Comment by drejc** [comment]
Lets wait and accumulate samo additional bugs/features. Rate of addoption
is quite slow if you do a lot of releases.

**Comment by jsirach** [comment]
Good evening,

I've seen the issue has been closed, but i'm seeing some odd behavior.

Using vertx web 3.8.0, updated rest.vertx to 0.8.9.

I'm having one path with a GET and a DELETE
1:
    @GET
    @Path("tokens/:tokenReferenceId")
2:
    @DELETE
    @Path("tokens/:tokenReferenceId")

I'm noticing after the update the DELETE annotated method is results in a 404. But after adding an empty body to my delete request, the DELETE annotated method is found again.

It looks like DELETE now requires a body to be able to be identified.

For now for me it's not a problem because my calls are made generic in my front-end, so adding an empty object is not that big of a deal. But it was unexpected.

You want me to open a new report?

**Comment by drejc** [comment]
Hm ... should not happen, will take a look.
