### ISSUE TITLE
How to disable logging caught exception as an Error

### ISSUE THREAD

**Issue by MohiuddinM** [zandero/rest.vertx#43]
One of my functions inside a Controller throws an Exception, and it is already caught by an exception handler (defined by RestRouter.getExceptionHandlers().register()), but it still shows up as an error 
```
[vert.x-eventloop-thread-0] ERROR RestRouter - Handling exception: 
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.zandero.rest.RestRouter.lambda$null$2(RestRouter.java:472)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by drejc** [comment]
Not quite sure what you mean by "shows up as an error"? If you want to disable rest vert.x logging you can always set:

`<logger name="com.zandero.rest" level="OFF" />`

**Comment by MohiuddinM** [comment]
I am only logging Errors.

What I want is that rest router should not log exception as error if it already has a corresponding exception handler

**Comment by drejc** [comment]
Maybe a better solution would be to change the log level in this case to debug as in any case an exception handler will be invoked. The provided one or a generic one.

**Comment by MohiuddinM** [comment]
What I want to suggest is that we should check if there is an exception handler (non generic) for a particular exception or not. If there is then it should be logged as debug, otherwise as error.

**Comment by drejc** [comment]
Changed logging to DEBUG in case of provided exception handler, otherwise ERROR
