### ISSUE TITLE
Unable to write application/json if a JaxResponse is used

### ISSUE THREAD

**Issue by dankristensen** [zandero/rest.vertx#6]
When i have a method returning a javax.ws.rs.core.Response, it is not possible to have the data returned as Json, due to the condition below in JaxResponseWriter class. Is there any reason for this?

				if (writer != null && !(writer instanceof JsonResponseWriter)) {
					writer.write(jax.getEntity(), request, response);
				}
				else {
					response.end(jax.getEntity().toString());
				}

**Comment by drejc** [comment]
Hm looking at this ...  !(writer instanceof JsonResponseWriter) it seems obsolete from some older code ... must check. 

Can you provide a code snippet so I can recreate the issue?

**Comment by drejc** [comment]
Jap you are correct ... this is bug ... or a relict of some older code. 
Have fixed the issue and will release a new version 0.7.1 (should be available in one hour or so)

**Comment by dankristensen** [comment]
Wow. That was fast. Thank you so much.

**Comment by drejc** [comment]
No problem ... this was a simple fix ...

**Comment by dankristensen** [comment]
It looks like i cannot build the project now.  Tests in this class is failing with: 
java.lang.NoSuchMethodError: com.zandero.utils.ResourceUtils.getString(Ljava/io/InputStream;ILjava/lang/String;)Ljava/lang/String;
	at com.zandero.http.HttpUtils.getContentAsString(HttpUtils.java:360)
	at com.zandero.rest.RouteRegistrationTest.registerTwoRoutesTest(RouteRegistrationTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeTestMethod(VertxUnitRunner.java:95)
	at io.vertx.ext.unit.junit.VertxUnitRunner.lambda$invokeExplosively$0(VertxUnitRunner.java:114)
	at io.vertx.ext.unit.impl.TestContextImpl$Step.run(TestContextImpl.java:122)
	at io.vertx.ext.unit.impl.TestContextImpl$Step.access$600(TestContextImpl.java:30)
	at io.vertx.ext.unit.impl.TestContextImpl.run(TestContextImpl.java:221)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeExplosively(VertxUnitRunner.java:130)
	at io.vertx.ext.unit.junit.VertxUnitRunner.access$000(VertxUnitRunner.java:39)
	at io.vertx.ext.unit.junit.VertxUnitRunner$1.evaluate(VertxUnitRunner.java:84)
	at io.vertx.ext.unit.junit.VertxUnitRunner$2.evaluate(VertxUnitRunner.java:196)
	at io.vertx.ext.unit.junit.VertxUnitRunner$3.evaluate(VertxUnitRunner.java:211)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by drejc** [comment]
Check if you have the latest version ... and try `mvn clean test`, tests on my side are all OK. I have updated some references in pom.xml ... 
You can try if the 0.7.1 version is available (it takes about an hour for maven central)

**Comment by dankristensen** [comment]
Ok.  Will do so and let you know

**Comment by dankristensen** [comment]
Nope still fails. I think maybe this is the problem:

        <version.zandero.http>[1.0,)</version.zandero.http>

It is using version 1.0, and i think it should be 1.2, which is the latest version. Could it be you had a local version of this on your machine?

**Comment by drejc** [comment]
Hm [1.0,) means it will take the latest available version found ... so 1.2 should be taken.
But I see that 1.2 is not visible on maven central ... will re-release this version.

**Comment by drejc** [comment]
Try now ... it should work

**Comment by dankristensen** [comment]
After removal of all local maven zandero artifacts, it worked. All tests are green now. Thanx

**Comment by drejc** [comment]
Cool ...
