### ISSUE TITLE
Cannot use null enum value in REST endpoint url

### ISSUE THREAD

**Issue by activey** [zandero/rest.vertx#79]
Hi,

We like your library very much! But ...
We have a rest endpoint defined with an enum value as query param. Unfortunately it does not really work well when passing null enum value:

```
Caused by: java.lang.IllegalArgumentException: Could not construct: class com.test.EnumValue with default value: 'null', must provide String only or primitive type constructor, static fromString() or valueOf() methods!
    at com.zandero.rest.reader.GenericValueReader.read(GenericValueReader.java:17)
    at com.zandero.rest.data.ArgumentProvider.getArguments(ArgumentProvider.java:106)
    ... 48 common frames omitted
```

Just saying ;)

**Comment by activey** [comment]
Allright, we did it with implementing fromString() ;)

**Comment by drejc** [comment]
Can you provide some code/working example? Hard to figure out what the
problem is without.
